from pathlib import Path

DEFAULT_LIVES = 3
EXPORT_DIR_DEFAULT = "game_database"
CSV_LABEL_FILE = "labels/id_mapping.csv"
CSV_FALLBACK_FILE = "id_mapping.csv"
AUDIO_SUBDIR = "audio"
LOGO_PATH = "assets/logo.png"
INSTITUTION_NAME = "University of Eastern Finland"

TEXTS = {
    "page_title": "Fake One Out",
    "page_icon": "🎙️",
    "hero_title": "Fake One Out",
    "hero_sub": (
        "You are invited to participate in a game exploring how well people can distinguish "
        "real human speech from AI-generated speech.<br><br>"
        "In each round, you will hear two audio clips. One is a recording of a real human voice; "
        "the other is generated by an AI text-to-speech system. "
        "Your task is to identify which clip is the real human voice.<br><br>"
        "Both clips may have audio processing applied. This is intentional; focus on identifying "
        "the human voice, not audio quality.<br><br>"
        "Playing is voluntary and anonymous- you can enter under any username you want, as it will not be saved.<br>"
        "At the end, you can choose whether to share your results with us."
    ),
    "rules": [
        "Use headphones for the best experience.",
        "Listen to <b>both</b> clips before answering. You may replay each as many times as you need.",
        "Select the clip you believe is the <b>real human voice</b>.",
        f"The session ends after {DEFAULT_LIVES} incorrect answers. Aim for doing your best. There are a total of 50 rounds.",
        "You may end the session at any time using the button at the bottom of the screen.",
    ],
    "feedback_correct": "Correct.",
    "feedback_wrong": "Incorrect.<br>",
    "lives_lost_note": "{} {} remaining.",
    "game_over_note": "No lives remaining. Session complete.",
    "leaderboard_label": "SESSION LEADERBOARD",
    "how_to_play_label": "Instructions",
    "round_label": "ROUND {}: WHICH CLIP IS THE REAL HUMAN VOICE?",
    "btn_start": "BEGIN SESSION",
    "btn_next": "NEXT ROUND",
    "btn_quit": "END SESSION & SEE RESULTS",
    "btn_play_again": "START A NEW SESSION",
    "btn_clip_a": "Clip A is the real voice",
    "btn_clip_b": "Clip B is the real voice",
    "error_no_db": "Audio database not found in `{}`. Please contact the researcher.",
    "error_load_audio": "Audio clips could not be loaded. Please try again or contact the researcher.",
    "consent_badge": "BEFORE YOU GO",
    "consent_title": "Would you like to share your results with researchers?",
    "consent_intro": (
         f"We are researchers at the {INSTITUTION_NAME} studying how well people detect AI-generated speech." 
        "Your results could help us. Participation is entirely voluntary. You may decline to share your data without any consequence. "
        "Please read the information below before deciding."
    ),
    "consent_data_label": "DATA COLLECTED IF YOU CONSENT",
    "consent_data_items": [
        "A randomly generated session ID. This cannot be linked to your identity.",
        "Your total score, accuracy percentage, and number of rounds completed.",
        "Per-round data: which clip was real, which you selected, and the audio processing applied.",
    ],
    "consent_no_pii": (
        "Your display name is used only for the local leaderboard and is never transmitted to researchers."
    ),
    "consent_purpose": (
        f"Data will be used solely for academic research on perception of AI-generated speech at the {INSTITUTION_NAME} "
        "and may be reported in scientific publications at the aggregate level."
    ),
    "consent_withdraw": (
        "Because no identifying information is collected, it is not possible to withdraw your data "
        "after submission. You may choose not to share your data without affecting your participation."
        "If you want any additional information, you can get in contact with the resposible researcher at lerscoi@uef.fi."
    ),
    "btn_consent_yes": "I CONSENT - SHARE MY RESULTS",
    "btn_consent_no": "DECLINE - DO NOT SHARE MY RESULTS",
    "consent_success": "✓ Your results have been submitted. Thank you for contributing to research!",
    "consent_fail": "Your results were not saved. Thank you for participating!",
}

TEXTS_FI = {
    "page_title": "Fake One Out",
    "page_icon": "🎙️",
    "hero_title": "Fake One Out",
    "hero_sub": (
        "Sinut on kutsuttu osallistumaan peliin, jossa tutkitaan, kuinka hyvin ihmiset pystyvät erottamaan"
        "aito ihmisen puhe vs. tekoälyn tuottama puhe.<br><br>"
        "Jokaisella kierroksella kuulet kaksi ääniklippiä. Toinen on todellisen ihmisäänen tallenne; "
        "toinen on tuotettu tekoälyn tekstistä puheeksi -järjestelmällä."
        "Tehtäväsi on tunnistaa, kumpi klippi on todellinen ihmisääni.<br><br>"
        "Molempiin klippeihin on saatettu soveltaa äänenkäsittelyä. Tämä on tarkoituksellista; keskity tunnistamaan "
        "ihmisen ääni, älä äänenlaatua.<br><br>"
        "Osallistuminen on vapaaehtoista ja anonyymiä: voit käyttää mitä tahansa käyttäjänimeä, sillä sitä ei tallenneta.<br>"
        "Lopuksi voit valita, haluatko jakaa tuloksesi kanssamme."
    ),
    "rules": [
        "Käytä kuulokkeita parhaan kokemuksen saamiseksi.",
        "Kuuntele <b>molemmat</b> ääninäytteet ennen vastaamista. Voit toistaa kumpaakin niin monta kertaa kuin tarvitset.",
        "Valitse se ääninäyte, jonka uskot olevan <b>aito ihmisääni</b>.",
        f"Istunto päättyy {DEFAULT_LIVES} virheellisen vastauksen jälkeen. Yritä tehdä parhaasi. Kierroksia on yhteensä 50.",
        "Voit lopettaa istunnon milloin tahansa näytön alareunassa olevalla painikkeella.",
    ],
    "feedback_correct": "Oikein. Äänite {} oli aito ihmisen ääni.",
    "feedback_wrong": "Väärin. Ääniklippi {} oli tekoälyn tuottama ääni.<br>",
    "lives_lost_note": "{} {} jäljellä.",
    "game_over_note": "Elämiä ei ole jäljellä. Istunto on päättynyt.",
    "leaderboard_label": "SESSION LEADERBOARD",
    "how_to_play_label": "Ohjeet",
    "round_label": "ROUND {}: MIKÄ ÄÄNENÄYTE ON AITO IHMISÄÄNI?",
    "btn_start": "ALOITA ISTUNTO",
    "btn_next": "SEURAAVA KIERROS",
    "btn_quit": "LOPETA ISTUNTO JA KATSO TULOS",
    "btn_play_again": "ALOITA UUSI ISTUNTO",
    "btn_clip_a": "Äänite A on aito ääni",
    "btn_clip_b": "Klippi B on aito ääni",
    "error_no_db": "Audio database not found in `{}`. Please contact the researcher.",
    "error_load_audio": "Audio clips could not be loaded. Please try again or contact the researcher.",
    "consent_badge": "BEFORE YOU GO",
    "consent_title": "Haluaisitko jakaa tuloksesi tutkijoiden kanssa?",
    "consent_intro": (
         f"Olemme {INSTITUTION_NAME} -laitoksen tutkijoita, jotka tutkivat, kuinka hyvin ihmiset tunnistavat tekoälyn tuottaman puheen."
        "Tuloksesi voivat auttaa meitä. Osallistuminen on täysin vapaaehtoista. Voit kieltäytyä jakamasta tietojasi ilman, että siitä aiheutuu sinulle mitään seurauksia."
        "Lue alla olevat tiedot ennen kuin teet päätöksesi."
    ),
    "consent_data_label": "DATA COLLECTED IF YOU CONSENT",
    "consent_data_items": [
        "Satunnaisesti luotu istuntotunnus. Tätä ei voida yhdistää henkilöllisyyteesi.",
        "Kokonaistuloksesi, tarkkuusprosenttisi ja suoritettujen kierrosten määrä.",
        "Kierroskohtaiset tiedot: mikä ääniklippi oli aito, minkä valitsit ja millaista äänenkäsittelyä sovellettiin.",
    ],
    "consent_no_pii": (
        "Näytönimesi käytetään ainoastaan paikallisessa tulostaulussa, eikä sitä koskaan välitetä tutkijoille."
    ),
    "consent_purpose": (
        f"Tietoja käytetään yksinomaan {INSTITUTION_NAME}:ssa tehtävään akateemiseen tutkimukseen, joka koskee tekoälyn tuottaman puheen havaitsemista"
        "ja niitä saatetaan esittää tieteellisissä julkaisuissa aggregoidussa muodossa."
    ),
    "consent_withdraw": (
         "Koska tunnistettavia tietoja ei kerätä, tietojasi ei ole mahdollista poistaa"
        "lähettämisen jälkeen. Voit päättää olla jakamatta tietojasi ilman, että se vaikuttaa osallistumiseesi."
        "Jos haluat lisätietoja, voit ottaa yhteyttä vastuulliseen tutkijaan osoitteessa lerscoi@uef.fi."
    ),
    "btn_consent_yes": "HYVÄKSYN - JAA TULOKSENI",
    "btn_consent_no": "KIELTÄYDYN - ÄLÄ JAA TULOKSIAANI",
    "consent_success": "✓ Tuloksesi on lähetetty. Kiitos, että osallistuit tutkimukseen!",
    "consent_fail": "Tuloksiasi ei tallennettu. Kiitos osallistumisestasi!",
}
