from pathlib import Path

DEFAULT_LIVES = 3
EXPORT_DIR_DEFAULT = "game_database"
CSV_LABEL_FILE = "labels/id_mapping.csv"
CSV_FALLBACK_FILE = "id_mapping.csv"
AUDIO_SUBDIR = "audio"
LOGO_PATH = "assets/logo.png"
INSTITUTION_NAME = "University of Eastern Finland"

TEXTS = {
    "page_title": "Fake One Out",
    "page_icon": "🎙️",
    "hero_title": "Fake One Out",
    "hero_sub": (
        "You are invited to participate in a game exploring how well people can distinguish "
        "real human speech from AI-generated speech.<br><br>"
        "In each round, you will hear two audio clips. One is a recording of a real human voice; "
        "the other is generated by an AI text-to-speech system. "
        "Your task is to identify which clip is the real human voice.<br><br>"
        "Both clips may have audio processing applied. This is intentional; focus on identifying "
        "the human voice, not audio quality.<br><br>"
        "Playing is voluntary and anonymous- you can enter under any username you want, as it will not be saved.<br>"
        "At the end, you can choose whether to share your results with us."
    ),
    "rules": [
        "Use headphones for the best experience.",
        "Listen to <b>both</b> clips before answering. You may replay each as many times as you need.",
        "Select the clip you believe is the <b>real human voice</b>.",
        f"The session ends after {DEFAULT_LIVES} incorrect answers. Aim for doing your best. There are a total of 50 rounds.",
        "You may end the session at any time using the button at the bottom of the screen.",
    ],
    "feedback_correct": "Correct. Clip {} was the real human voice.",
    "feedback_wrong": "Incorrect. Clip {} was the AI-generated voice.<br>",
    "lives_lost_note": "{} {} remaining.",
    "game_over_note": "No lives remaining. Session complete.",
    "leaderboard_label": "SESSION LEADERBOARD",
    "how_to_play_label": "Instructions",
    "round_label": "ROUND {}: WHICH CLIP IS THE REAL HUMAN VOICE?",
    "btn_start": "BEGIN SESSION",
    "btn_next": "NEXT ROUND",
    "btn_quit": "END SESSION & SEE RESULTS",
    "btn_play_again": "START A NEW SESSION",
    "btn_clip_a": "Clip A is the real voice",
    "btn_clip_b": "Clip B is the real voice",
    "error_no_db": "Audio database not found in `{}`. Please contact the researcher.",
    "error_load_audio": "Audio clips could not be loaded. Please try again or contact the researcher.",
    "consent_badge": "BEFORE YOU GO",
    "consent_title": "Would you like to share your results with researchers?",
    "consent_intro": (
         f"We are researchers at the {INSTITUTION_NAME} studying how well people detect AI-generated speech." 
        "Your results could help us. Participation is entirely voluntary. You may decline to share your data without any consequence. "
        "Please read the information below before deciding."
    ),
    "consent_data_label": "DATA COLLECTED IF YOU CONSENT",
    "consent_data_items": [
        "A randomly generated session ID. This cannot be linked to your identity.",
        "Your total score, accuracy percentage, and number of rounds completed.",
        "Per-round data: which clip was real, which you selected, and the audio processing applied.",
    ],
    "consent_no_pii": (
        "Your display name is used only for the local leaderboard and is never transmitted to researchers."
    ),
    "consent_purpose": (
        f"Data will be used solely for academic research on perception of AI-generated speech at the {INSTITUTION_NAME} "
        "and may be reported in scientific publications at the aggregate level."
    ),
    "consent_withdraw": (
        "Because no identifying information is collected, it is not possible to withdraw your data "
        "after submission. You may choose not to share your data without affecting your participation."
        "If you want any additional information, you can get in contact with the resposible researcher at lerscoi@uef.fi."
    ),
    "btn_consent_yes": "I CONSENT - SHARE MY RESULTS",
    "btn_consent_no": "DECLINE - DO NOT SHARE MY RESULTS",
    "consent_success": "✓ Your results have been submitted. Thank you for contributing to research!",
    "consent_fail": "Your results were not saved. Thank you for participating!",
}